const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');
const overlay=document.getElementById('overlay'),select=document.getElementById('select'),finish=document.getElementById('finish');
const keys={};let state='menu',chosen='leo',camX=0,paused=false,startedAt=Date.now();
const W=canvas.width,H=canvas.height,TS=36,gravity=.72; const levelW=4200;
const chars={leo:{color:'#3aa0ff',speed:4.2,jump:14.5},noah:{color:'#ff8e3c',speed:5,jump:14},zipp:{color:'#8a57ff',speed:4,jump:15.5},luna:{color:'#ff77c7',speed:4.2,jump:16.5}};
let player,crystals,coins,enemies,platforms,checkpoint,won=false;
function reset(){ const c=chars[chosen]; player={x:80,y:280,w:28,h:42,vx:0,vy:0,on:false,life:3,energy:100,color:c.color,speed:c.speed,jump:c.jump,cr:0,co:0}; checkpoint={x:80,y:280}; won=false; startedAt=Date.now();
platforms=[]; for(let x=0;x<levelW;x+=TS) platforms.push({x,y:470,w:TS,h:70,type:x%144==0?'grass2':'grass'}); addPlat(260,390,5);addPlat(580,335,4);addPlat(860,395,4);addPlat(1160,325,5);addPlat(1520,385,5);addPlat(1900,320,4);addPlat(2300,390,6);addPlat(2760,330,5);addPlat(3230,380,6);addPlat(3650,330,4);
crystals=[...itemLine(300,350,4,55,'crystal'),...itemLine(620,292,4,55,'crystal'),...itemLine(1200,282,5,55,'crystal'),...itemLine(2350,350,6,45,'crystal'),...itemLine(3260,335,5,50,'crystal')];
coins=[...itemLine(90,415,7,45,'coin'),...itemLine(900,350,5,45,'coin'),...itemLine(1600,340,5,45,'coin'),...itemLine(2800,285,5,45,'coin')];
enemies=[enemy(760,435),enemy(1410,435),enemy(2100,435),enemy(3020,435)]; }
function addPlat(x,y,n){for(let i=0;i<n;i++) platforms.push({x:x+i*TS,y,w:TS,h:TS,type:'dirt'});}function itemLine(x,y,n,g,type){return Array.from({length:n},(_,i)=>({x:x+i*g,y,type,taken:false,bob:Math.random()*6.28}))}function enemy(x,y){return{x,y,w:30,h:25,vx:1.2,alive:true,min:x-100,max:x+120}}
window.onkeydown=e=>{keys[e.key.toLowerCase()]=true;if(e.key===' ')e.preventDefault(); if(e.key.toLowerCase()==='p')paused=!paused; if(e.key.toLowerCase()==='r'&&state==='play'){player.x=checkpoint.x;player.y=checkpoint.y;player.vx=0;player.vy=0;}}; window.onkeyup=e=>keys[e.key.toLowerCase()]=false;
document.getElementById('newGame').onclick=()=>{overlay.classList.add('hidden');select.classList.remove('hidden');};document.getElementById('commands').onclick=()=>document.getElementById('commandBox').classList.toggle('hidden');document.querySelectorAll('.card').forEach(b=>b.onclick=()=>{document.querySelectorAll('.card').forEach(c=>c.classList.remove('selected'));b.classList.add('selected');chosen=b.dataset.id;});document.querySelector('.card').classList.add('selected');document.getElementById('start').onclick=()=>{select.classList.add('hidden');state='play';reset();requestAnimationFrame(loop)};document.getElementById('again').onclick=()=>{finish.classList.add('hidden');overlay.classList.remove('hidden');state='menu'};
function loop(){update();draw();if(state==='play')requestAnimationFrame(loop)}
function update(){if(paused||won)return; const left=keys['arrowleft']||keys['a'],right=keys['arrowright']||keys['d'],jump=keys[' ']||keys['w']||keys['arrowup']; player.vx=(right-left)*player.speed; if(jump&&player.on){player.vy=-player.jump;player.on=false;} player.vy+=gravity; move(player); camX=Math.max(0,Math.min(levelW-W,player.x-W*.35)); collect(crystals); collect(coins); enemies.forEach(en=>{if(!en.alive)return;en.x+=en.vx;if(en.x<en.min||en.x>en.max)en.vx*=-1;if(hit(player,en)){ if(player.vy>2&&player.y+player.h<en.y+15){en.alive=false;player.vy=-10}else{damage();}}}); if(player.y>H+200)damage(true); if(player.x>3990)levelEnd();}
function move(o){o.x+=o.vx; platforms.forEach(p=>{if(hit(o,p)){if(o.vx>0)o.x=p.x-o.w;if(o.vx<0)o.x=p.x+p.w;}}); o.y+=o.vy;o.on=false; platforms.forEach(p=>{if(hit(o,p)){if(o.vy>0){o.y=p.y-o.h;o.vy=0;o.on=true}else if(o.vy<0){o.y=p.y+p.h;o.vy=0}}});}
function collect(arr){arr.forEach(it=>{if(!it.taken&&Math.abs((player.x+14)-it.x)<30&&Math.abs((player.y+20)-it.y)<35){it.taken=true;if(it.type==='crystal')player.cr++;else player.co++;}})}function damage(fall=false){player.life--;player.x=checkpoint.x;player.y=checkpoint.y;player.vx=0;player.vy=0;if(player.life<=0){player.life=3;reset();}if(fall)player.energy=Math.max(0,player.energy-10)}function levelEnd(){won=true;state='finish';document.getElementById('scoreText').innerText=`Cristalli ${player.cr}/${crystals.length} · Monete ${player.co}/${coins.length} · Tempo ${Math.floor((Date.now()-startedAt)/1000)}s`;finish.classList.remove('hidden')}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function draw(){ctx.clearRect(0,0,W,H);sky();ctx.save();ctx.translate(-camX,0);decor();platforms.forEach(tile);crystals.forEach(item);coins.forEach(item);enemies.forEach(drawEnemy);flag(4020,360);drawPlayer();ctx.restore();hud();if(paused){ctx.fillStyle='#0008';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='50px Arial';ctx.fillText('PAUSA',390,270)}}
function sky(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#6ccfff');g.addColorStop(.65,'#c7f5ff');g.addColorStop(1,'#78d96e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<8;i++)cloud((i*210-(camX*.18)%210),70+(i%3)*55,1+(i%2)*.4);mountain(80-(camX*.08)%600,470,'#7ec2dd');mountain(420-(camX*.08)%600,470,'#83d4b5')}
function cloud(x,y,s){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,24*s,0,7);ctx.arc(x+28*s,y-8*s,30*s,0,7);ctx.arc(x+65*s,y,22*s,0,7);ctx.fill()}function mountain(x,y,c){ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+180,y-230);ctx.lineTo(x+360,y);ctx.fill();}
function decor(){for(let x=120;x<levelW;x+=380){tree(x,434);flower(x+70,455);bush(x+135,450)}for(let x=0;x<levelW;x+=520){ctx.fillStyle='#ffffff90';ctx.fillRect(x+230,250,120,14)}}function tree(x,y){ctx.fillStyle='#7b4628';ctx.fillRect(x,y-80,28,80);ctx.fillStyle='#2cc66b';for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(x+14,y-90-i*22,48-i*7,0,7);ctx.fill()}}function flower(x,y){ctx.fillStyle='#ffeb3b';ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fill();ctx.fillStyle='#ff70b8';ctx.beginPath();ctx.arc(x-7,y,6,0,7);ctx.arc(x+7,y,6,0,7);ctx.arc(x,y-7,6,0,7);ctx.arc(x,y+7,6,0,7);ctx.fill()}function bush(x,y){ctx.fillStyle='#27a951';ctx.beginPath();ctx.arc(x,y,20,0,7);ctx.arc(x+22,y,18,0,7);ctx.fill()}
function tile(p){ctx.fillStyle=p.type==='grass'||p.type==='grass2'?'#35bf52':'#9b6238';ctx.fillRect(p.x,p.y,p.w,p.h);if(p.type.startsWith('grass')){ctx.fillStyle='#7eff67';ctx.fillRect(p.x,p.y,p.w,8)}ctx.strokeStyle='#0002';ctx.strokeRect(p.x,p.y,p.w,p.h)}
function item(it){if(it.taken)return;let y=it.y+Math.sin(Date.now()/250+it.bob)*5;if(it.type==='coin'){ctx.fillStyle='#ffd33d';ctx.beginPath();ctx.ellipse(it.x,y,11,15,0,0,7);ctx.fill();ctx.strokeStyle='#b76f00';ctx.stroke()}else{ctx.fillStyle='#52f3ff';ctx.beginPath();ctx.moveTo(it.x,y-17);ctx.lineTo(it.x+14,y);ctx.lineTo(it.x,y+18);ctx.lineTo(it.x-14,y);ctx.closePath();ctx.fill();ctx.strokeStyle='#1b83d1';ctx.stroke()}}
function drawEnemy(en){if(!en.alive)return;ctx.fillStyle='#65df5a';ctx.beginPath();ctx.ellipse(en.x+15,en.y+15,18,14,0,0,7);ctx.fill();ctx.fillStyle='#123';ctx.fillRect(en.x+8,en.y+10,4,4);ctx.fillRect(en.x+20,en.y+10,4,4)}function flag(x,y){ctx.fillStyle='#6e3f24';ctx.fillRect(x,y,10,110);ctx.fillStyle='#ffd33d';ctx.beginPath();ctx.moveTo(x+10,y);ctx.lineTo(x+78,y+25);ctx.lineTo(x+10,y+50);ctx.fill()}function drawPlayer(){ctx.fillStyle=player.color;ctx.fillRect(player.x,player.y+10,player.w,player.h-10);ctx.fillStyle='#ffcf9e';ctx.fillRect(player.x+5,player.y,18,18);ctx.fillStyle='#38245f';ctx.fillRect(player.x+8,player.y+6,4,4);ctx.fillRect(player.x+18,player.y+6,4,4);ctx.fillStyle='#2f2450';ctx.fillRect(player.x-3,player.y+player.h-5,13,6);ctx.fillRect(player.x+18,player.y+player.h-5,13,6)}
function hud(){ctx.fillStyle='#172055cc';ctx.fillRect(18,16,330,74);ctx.fillStyle='#fff';ctx.font='bold 20px Arial';ctx.fillText('AND: Tiny Kingdoms',34,42);ctx.font='18px Arial';ctx.fillText('❤'.repeat(player?.life||3),34,70);ctx.fillText(`💎 ${player?.cr||0}/${crystals?.length||0}`,145,70);ctx.fillText(`🟡 ${player?.co||0}/${coins?.length||0}`,255,70);ctx.fillStyle='#172055cc';ctx.fillRect(770,16,170,40);ctx.fillStyle='#fff';ctx.font='16px Arial';ctx.fillText('P pausa · R checkpoint',785,42)}
